name: Debug Slack Webhook

on:
  push:
    branches:
      - fix/slack-webhook-part-3  # Replace with your specific branch name

jobs:
  debug-slack-webhook:
    runs-on: ubuntu-latest

    steps:
    - name: Debug Slack Webhook
      run: |
        json="{\"text\": \"<!here> CI is failing in <https://github.com/cds-snc/notification-admin/actions/runs/${{ github.run_id }}|notification-admin> !\"}"
        echo "Sending: $json"  # Debug print
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}
