name: Generate SBOM

on:
  pull_request:
    branches:
      - main
    paths:
      - package.json
      - requirements.txt
      - .github/workflows/generate-sbom.yaml
  push:
    branches:
      - main
    paths:
      - package.json
      - requirements.txt
      - .github/workflows/generate-sbom.yaml

jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate app SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@14ab23f07437d642594c56003db1f4bd34e54bbb # renovate: tag=v1
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: notification-admin/app
          project_type: python

      - name: Generate front-end SBOM
        uses: cds-snc/security-tools/.github/actions/generate-sbom@14ab23f07437d642594c56003db1f4bd34e54bbb # renovate: tag=v1
        with:
          dependency_track_api_key: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          project_name: notification-admin/frontend
          project_type: node          
